server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  config:
    activate:
      on-profile: main

  #rabbitMQ
  main:
    rabbitmq:
      host: localhost
      port: 5672
      username: jaemin
      password: jaemin

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/concu?rewriteBatchedStatements=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000
      maximum-pool-size: 5
      pool-name: jm-admin-pool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
        id:
          new_generator_mappings: false


    database-platform: org.hibernate.dialect.MySQL8Dialect